"""Assembly point for the LangChain RAG pipeline."""

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import Runnable, RunnableLambda
from langchain_openai import ChatOpenAI

from src.ingestion import create_vector_store, load_documents, split_documents
from src.prompts import create_prompt_template
from src.retrieval import print_retrieval_debug, retrieve_with_scores

LLM_MODEL = "gpt-4o-mini"


def format_documents(documents: list[Document]) -> str:
    """Combine retrieved document chunks into prompt context.

    Args:
        documents: The document chunks selected during retrieval.

    Returns:
        The chunk text joined with blank lines between documents.
    """
    return "\n\n".join(document.page_content for document in documents)


def create_prompt_inputs(question: str, vector_store: FAISS) -> dict[str, str]:
    """Retrieve scored chunks, print debug details, and prepare prompt inputs.

    Args:
        question: The financial research question to answer.
        vector_store: The FAISS index containing embedded document chunks.

    Returns:
        A mapping containing the original question and retrieved text context.
    """
    retrieved_documents = retrieve_with_scores(question, vector_store)
    print_retrieval_debug(retrieved_documents)
    context = format_documents([result["document"] for result in retrieved_documents])
    return {"context": context, "question": question}


def create_rag_chain() -> Runnable[str, str]:
    """Build a RAG chain that retrieves context and generates a response.

    The chain loads and indexes the financial corpus, retrieves scored chunks
    for each question, prints their debug information, inserts the chunk text
    into the prompt, and sends the prompt to the language model.

    Returns:
        A LangChain runnable that accepts a question string and returns a
        generated response string.
    """
    documents = load_documents()
    chunks = split_documents(documents)
    vector_store = create_vector_store(chunks)
    prompt = create_prompt_template()
    llm = ChatOpenAI(model=LLM_MODEL)

    def prepare_prompt_inputs(question: str) -> dict[str, str]:
        """Build prompt inputs for one question using the prepared vector store.

        Args:
            question: The financial research question to answer.

        Returns:
            A mapping containing the question and its retrieved text context.
        """
        return create_prompt_inputs(question, vector_store)

    return RunnableLambda(prepare_prompt_inputs) | prompt | llm | StrOutputParser()


def run_pipeline(question: str) -> str:
    """Generate a response to a financial research question with the RAG chain.

    Args:
        question: The financial research question to answer.

    Returns:
        The response generated by the assembled RAG chain.
    """
    rag_chain = create_rag_chain()
    return rag_chain.invoke(question)
